site_name: New Welsh Mesh
site_url: https://welshmesh.pysgod.xyz/
edit_uri: edit/main/docs/

theme:
  name: material
  logo: nwm-white.png
  favicon: nwm-white.png
  palette: 
    - scheme: default
      primary: custom 
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - navigation.footer

extra_css:
  - stylesheets/style.css

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/4VhKqbH39W
  copyright: Copyright &copy; 2026 [Pysgod Media]{pysgod.xyz/welsh/copyright}
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better. Even though I have no idea how to do any of that,
      Its good to make sure of your preference
  

nav:
  - Home: index.md
  - Documentation:
    - Getting Started: 
        - Introduction: docs/getting-started.md
        - Node Settings: docs/node-settings.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list  # This is needed to make your { width="35%" } and buttons work!

use_directory_urls: true
